In [1]:
import datetime as dt
from dotenv import load_dotenv
import pandas as pd
from backtesting import Strategy, Backtest
from backtesting.lib import crossover
from securities_load.securities.postgresql_database_functions import sqlalchemy_engine
from securities_load.securities.securities_table_functions import retrieve_ohlcv_from_to

ImportError: cannot import name 'Strategy' from 'backtesting' (unknown location)

In [ ]:
def localData(exchange, ticker, years):
    load_dotenv()
    engine = sqlalchemy_engine()
    exchange_code = "XNAS"
    ticker = "GOOG"
    num_of_years = 10
    start_date = dt.datetime.now() - dt.timedelta(int(365.25 * num_of_years))
    start_date_str = dt.datetime.strftime(start_date, "%Y-%m-%d")
    end_date = dt.datetime.now()
    end_date_str = dt.datetime.strftime(end_date, "%Y-%m-%d")
    # print(start_date)
    # print(end_date)
    df = retrieve_ohlcv_from_to(
        engine,
        exchange_code=exchange_code,
        ticker=ticker,
        start_date=start_date_str,
        end_date=end_date_str,
    )
    print(f"\nInfo: {df.info()}")
    print(df.head(3))
    # print(df.tail(3))
    df.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]
    print(df.info())
    return df

In [5]:
df = localData(exchange="XNAS", ticker="GOOG", years=1)

Exchange_id is: 2
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1879 entries, 2018-10-26 to 2026-04-21
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1879 non-null   object
 1   open    1879 non-null   float64
 2   high    1879 non-null   float64
 3   low     1879 non-null   float64
 4   close   1879 non-null   float64
 5   volume  1879 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 102.8+ KB

Info: None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1879 entries, 2018-10-26 to 2026-04-21
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1879 non-null   object
 1   Open    1879 non-null   float64
 2   High    1879 non-null   float64
 3   Low     1879 non-null   float64
 4   Close   1879 non-null   float64
 5   Volume  1879 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 102.8+ KB
None

In [3]:
def SMA(values, n):
    """
    Return simple moving average of `values`, at
    each step taking into account `n` previous values.
    """
    return pd.Series(values).rolling(n).mean()

In [4]:
class SmaCross(Strategy):
    # Define the two MA lags as *class variables*
    # for later optimization
    n1 = 10
    n2 = 20
    
    def init(self):
        # Precompute the two moving averages
        self.sma1 = self.I(SMA, self.data.Close, self.n1)
        self.sma2 = self.I(SMA, self.data.Close, self.n2)
    
    def next(self):
        # If sma1 crosses above sma2, close any existing
        # short trades, and buy the asset
        if crossover(self.sma1, self.sma2):
            self.position.close()
            self.buy()

        # Else, if sma1 crosses below sma2, close any existing
        # long trades, and sell the asset
        elif crossover(self.sma2, self.sma1):
            self.position.close()
            self.sell()

In [5]:
bt = Backtest(localData("XNAS", "GOOG", 10), SmaCross, cash=10_000, commission=.002)
stats = bt.run()
stats

Exchange_id is: 2

Backtest.run:   0%|          | 0/1858 [00:00<?, ?bar/s]

/tmp/ipykernel_27500/2308637473.py:2: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  stats = bt.run()

Start                     2018-10-26 00:00:00
End                       2026-04-20 00:00:00
Duration                   2733 days 00:00:00
Exposure Time [%]                    98.34931
Equity Final [$]                   8162.25723
Equity Peak [$]                   11211.21993
Commissions [$]                    3201.91305
Return [%]                          -18.37743
Buy & Hold Return [%]                555.1549
Return (Ann.) [%]                    -2.68804
Volatility (Ann.) [%]                    29.5
CAGR [%]                             -1.85496
Sharpe Ratio                         -0.09112
Sortino Ratio                        -0.12831
Calmar Ratio                         -0.04639
Alpha [%]                           -87.21077
Beta                                  0.12399
Max. Drawdown [%]                   -57.94979
Avg. Drawdown [%]                    -19.2185
Max. Drawdown Duration     2460 days 00:00:00
Avg. Drawdown Duration      538 days 00:00:00
# Trades                                  100
Win Rate [%]                             37.0
Best Trade [%]                       40.86646
Worst Trade [%]                     -16.24968
Avg. Trade [%]                       -0.23039
Max. Trade Duration         116 days 00:00:00
Avg. Trade Duration          27 days 00:00:00
Profit Factor                         1.02403
Expectancy [%]                        0.06527
SQN                                  -0.37562
Kelly Criterion                      -0.04022
_strategy                            SmaCross
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

In [6]:
bt.plot()

GridPlot(id='p1320', ...)

In [7]:
%%time

stats = bt.optimize(n1=range(5, 30, 5),
                    n2=range(10, 70, 5),
                    maximize='Equity Final [$]',
                    constraint=lambda param: param.n1 < param.n2)
stats

Backtest.optimize:   0%|          | 0/50 [00:00<?, ?it/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1838 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1863 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1833 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1858 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1843 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1813 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1818 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1813 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1843 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1828 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1838 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1818 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1828 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1853 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1848 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1838 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1813 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1838 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1823 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1863 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1833 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1823 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1813 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1848 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1818 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1833 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1858 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1833 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1858 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1843 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1828 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1853 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1813 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1853 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1828 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1853 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1828 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1838 [00:00<?, ?bar/s]

Backtest.run:   0%|          | 0/1823 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1848 [00:00<?, ?bar/s]

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)
/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1637: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  for stats in (bt.run(**params)

Backtest.run:   0%|          | 0/1843 [00:00<?, ?bar/s]

CPU times: user 371 ms, sys: 248 ms, total: 619 ms
Wall time: 1.14 s

/home/ubuntuuser/miniconda3/envs/analysis/lib/python3.12/site-packages/backtesting/backtesting.py:1545: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  stats = self.run(**dict(zip(heatmap.index.names, best_params)))

Start                     2018-10-26 00:00:00
End                       2026-04-20 00:00:00
Duration                   2733 days 00:00:00
Exposure Time [%]                     95.5804
Equity Final [$]                  30532.16586
Equity Peak [$]                   37131.72586
Commissions [$]                    3176.23046
Return [%]                          205.32166
Buy & Hold Return [%]               559.89199
Return (Ann.) [%]                    16.15752
Volatility (Ann.) [%]                34.84163
CAGR [%]                             10.84031
Sharpe Ratio                          0.46374
Sortino Ratio                           0.821
Calmar Ratio                          0.40584
Alpha [%]                           134.12328
Beta                                  0.12716
Max. Drawdown [%]                   -39.81273
Avg. Drawdown [%]                    -4.54322
Max. Drawdown Duration     1269 days 00:00:00
Avg. Drawdown Duration       47 days 00:00:00
# Trades                                   53
Win Rate [%]                         52.83019
Best Trade [%]                      107.05003
Worst Trade [%]                     -18.14875
Avg. Trade [%]                        2.30343
Max. Trade Duration         245 days 00:00:00
Avg. Trade Duration          50 days 00:00:00
Profit Factor                         2.22524
Expectancy [%]                        3.26629
SQN                                   1.21735
Kelly Criterion                       0.27171
_strategy                 SmaCross(n1=25,n...
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

In [31]:
stats._strategy

In [32]:
stats.tail()

SQN                                                         1.217347
Kelly Criterion                                             0.271708
_strategy                                      SmaCross(n1=25,n2=35)
_equity_curve                        Equity  DrawdownPct Drawdown...
_trades                Size  EntryBar  ExitBar  EntryPrice  ExitP...
dtype: object

In [33]:
stats['_equity_curve']

                  Equity  DrawdownPct DrawdownDuration
2018-10-26  10000.000000     0.000000              NaT
2018-10-29  10000.000000     0.000000              NaT
2018-10-30  10000.000000     0.000000              NaT
2018-10-31  10000.000000     0.000000              NaT
2018-11-01  10000.000000     0.000000              NaT
...                  ...          ...              ...
2026-04-09  32549.345864     0.123409              NaT
2026-04-10  32618.245864     0.121553              NaT
2026-04-13  32248.305864     0.131516              NaT
2026-04-14  31043.085864     0.163974              NaT
2026-04-15  30630.745864     0.175079          16 days

[1875 rows x 3 columns]

In [17]:
stats['_trades']

,Size,EntryBar,ExitBar,EntryPrice,ExitPrice,SL,TP,PnL,Commission,ReturnPct,EntryTime,ExitTime,Duration,Tag,"Entry_SMA(C,25)","Exit_SMA(C,25)","Entry_SMA(C,35)","Exit_SMA(C,35)"
0,191,45,48,52.0500,53.8055,None,None,294.863699,40.436801,0.029660,2019-01-03,2019-01-08,5 days,None,52.17254,52.16542,52.123829,52.262457
1,-190,48,61,53.8055,54.0055,None,None,-78.968180,40.968180,-0.007725,2019-01-08,2019-01-28,20 days,None,52.16542,52.74540,52.262457,52.578914
2,188,61,140,54.0055,57.4245,None,None,600.874320,41.897680,0.059182,2019-01-28,2019-05-21,113 days,None,52.74540,59.79972,52.578914,59.964657
3,-187,140,177,57.4245,57.3430,None,None,-27.682545,42.923045,-0.002578,2019-05-21,2019-07-15,55 days,None,59.79972,55.32810,59.964657,55.016557
4,187,177,216,57.3430,60.2000,None,None,490.297918,43.961082,0.045723,2019-07-15,2019-09-09,56 days,None,55.32810,59.08526,55.016557,59.187829
5,-186,216,223,60.2000,61.3755,None,None,-263.869086,45.226086,-0.023566,2019-09-09,2019-09-18,9 days,None,59.08526,59.74884,59.187829,59.650214
6,179,223,251,61.3755,63.7725,None,None,384.260016,44.802984,0.034977,2019-09-18,2019-10-28,40 days,None,59.74884,61.43822,59.650214,61.449457
7,-178,251,256,63.7725,63.8225,None,None,-54.323820,45.423820,-0.004786,2019-10-28,2019-11-04,7 days,None,61.43822,61.83496,61.449457,61.760671
8,177,256,337,63.8225,69.9710,None,None,1040.921601,47.362899,0.092145,2019-11-04,2020-03-03,120 days,None,61.83496,72.69972,61.760671,72.784100
9,-176,337,375,69.9710,64.8000,None,None,862.656608,47.439392,0.070050,2020-03-03,2020-04-27,55 days,None,72.69972,59.73760,72.784100,59.147629
10,204,375,460,64.8000,80.4000,None,None,3123.158400,59.241600,0.236259,2020-04-27,2020-08-26,121 days,None,59.73760,76.29288,59.147629,76.387014
11,-203,460,463,80.4000,82.3945,None,None,-470.978067,66.094567,-0.028857,2020-08-26,2020-08-31,5 days,None,76.29288,77.00322,76.387014,76.885371
12,192,463,485,82.3945,74.2135,None,None,-1630.889472,60.137472,-0.103092,2020-08-31,2020-10-01,31 days,None,77.00322,76.58528,76.885371,77.077000
13,-191,485,503,74.2135,79.7835,None,None,-1122.696854,58.826854,-0.079204,2020-10-01,2020-10-27,26 days,None,76.58528,76.03452,77.077000,75.801029
14,164,503,554,79.7835,89.3035,None,None,1505.819464,55.460536,0.115084,2020-10-27,2021-01-11,76 days,None,76.03452,88.20586,75.801029,88.415657
15,-163,554,566,89.3035,92.1970,None,None,-530.809663,59.169163,-0.036466,2021-01-11,2021-01-28,17 days,None,88.20586,89.48898,88.415657,89.161971
16,152,566,604,92.1970,103.2685,None,None,1623.446488,59.421512,0.115845,2021-01-28,2021-03-24,55 days,None,89.48898,103.26774,89.161971,103.694743
17,-152,604,614,103.2685,113.8980,None,None,-1681.702616,66.018616,-0.107137,2021-03-24,2021-04-08,15 days,None,103.26774,104.59108,103.694743,104.281529
18,123,614,741,113.8980,138.8630,None,None,3008.515794,62.179206,0.214749,2021-04-08,2021-10-07,182 days,None,104.59108,140.66488,104.281529,141.196214
19,-122,741,761,138.8630,147.2000,None,None,-1086.913372,69.799372,-0.064158,2021-10-07,2021-11-04,28 days,None,140.66488,141.38130,141.196214,140.729400
20,108,761,790,147.2000,148.0770,None,None,30.936168,63.779832,0.001946,2021-11-04,2021-12-16,42 days,None,141.38130,146.62550,140.729400,146.846114
21,-107,790,808,148.0770,141.5545,None,None,635.926359,61.981141,0.040136,2021-12-16,2022-01-12,27 days,None,146.62550,144.26152,146.846114,144.318071
22,117,808,809,141.5545,141.8405,None,None,-32.852430,66.314430,-0.001984,2022-01-12,2022-01-13,1 days,None,144.26152,143.87794,144.318071,144.100186
23,-116,809,842,141.8405,135.9785,None,None,615.537992,64.454008,0.037411,2022-01-13,2022-03-03,49 days,None,143.87794,135.85260,144.100186,135.393400
24,126,842,849,135.9785,130.5730,None,None,-748.263978,67.170978,-0.043673,2022-03-03,2022-03-14,11 days,None,135.85260,133.45016,135.393400,134.065486
25,-126,849,862,130.5730,142.4485,None,None,-1565.114418,68.801418,-0.095131,2022-03-14,2022-03-31,17 days,None,133.45016,135.30430,134.065486,134.771143
26,104,862,881,142.4485,117.1150,None,None,-2688.673208,53.989208,-0.181488,2022-03-31,2022-04-28,28 days,None,135.30430,132.30286,134.771143,132.785214
27,-104,881,926,117.1150,107.5145,None,None,951.729064,46.722936,0.078139,2022-04-28,2022-07-05,68 days,None,132.30286,112.76534,132.785214,112.323729
28,122,926,935,107.5145,113.4400,None,None,668.998102,53.912898,0.051003,2022-07-05,2022-07-18,13 days,None,112.76534,112.47266,112.323729,113.136957
29,-121,935,941,113.4400,107.4300,None,None,673.759460,53.450540,0.049086,2022-07-18,2022-07-26,8 days,None,112.47266,113.11186,113.136957,112.702357
30,134,941,976,107.4300,105.4400,None,None,-323.709160,57.049160,-0.022487,2022-07-26,2022-09-14,50 days,None,113.11186,114.08760,112.702357,114.854571
31,-134,976,1038,105.4400,93.0900,None,None,1601.693960,53.206040,0.113362,2022-09-14,2022-12-12,89 days,None,114.08760,96.14560,114.854571,95.370286
32,169,1038,1050,93.0900,87.0300,None,None,-1085.020560,60.880560,-0.068968,2022-12-12,2022-12-29,17 days,None,96.14560,93.92960,95.370286,94.564000
33,-168,1050,1071,87.0300,97.8600,None,None,-1881.563040,62.123040,-0.128689,2022-12-29,2023-01-31,33 days,None,93.92960,92.88800,94.564000,92.552571
34,130,1071,1095,97.8600,95.4200,None,None,-367.452800,50.252800,-0.028884,2023-01-31,2023-03-07,35 days,None,92.88800,96.23320,92.552571,96.512286
35,-130,1095,1112,95.4200,101.4400,None,None,-833.783600,51.183600,-0.067216,2023-03-07,2023-03-30,23 days,None,96.23320,97.30400,96.512286,96.436000
36,114,1112,1179,101.4400,120.8900,None,None,2166.608760,50.691240,0.187355,2023-03-30,2023-07-07,99 days,None,97.30400,122.88200,96.436000,123.111143
37,-113,1179,1198,120.8900,128.3700,None,None,-901.572760,56.332760,-0.065998,2023-07-07,2023-08-03,27 days,None,122.88200,124.05400,123.111143,123.621714
38,100,1198,1250,128.3700,140.0300,None,None,1112.320000,53.680000,0.086650,2023-08-03,2023-10-17,75 days,None,124.05400,136.32200,123.621714,136.397429
39,-99,1250,1262,140.0300,129.5600,None,None,983.151180,53.378820,0.070919,2023-10-17,2023-11-02,16 days,None,136.32200,134.63160,136.397429,134.436857
40,115,1262,1270,129.5600,135.6500,None,None,639.351700,60.998300,0.042911,2023-11-02,2023-11-14,12 days,None,134.63160,133.52320,134.436857,134.076571
41,-115,1270,1285,135.6500,132.9000,None,None,254.483500,61.766500,0.016313,2023-11-14,2023-12-06,22 days,None,133.52320,134.40040,134.076571,133.645429
42,119,1285,1303,132.9000,138.6000,None,None,613.683000,64.617000,0.038804,2023-12-06,2024-01-03,28 days,None,134.40040,137.08040,133.645429,137.169429
43,-118,1303,1308,138.6000,142.5200,None,None,-528.904320,66.344320,-0.032339,2024-01-03,2024-01-10,7 days,None,137.08040,138.25760,137.169429,137.776000
44,111,1308,1343,142.5200,139.6100,None,None,-385.642860,62.632860,-0.024377,2024-01-10,2024-03-01,51 days,None,138.25760,144.91680,137.776000,145.461143
45,-111,1343,1366,139.6100,155.0800,None,None,-1782.591180,65.421180,-0.115030,2024-03-01,2024-04-04,34 days,None,144.91680,145.20360,145.461143,144.453143
46,88,1366,1451,155.0800,160.9450,None,None,460.499600,55.620400,0.033744,2024-04-04,2024-08-06,124 days,None,145.20360,179.43480,144.453143,180.159429
47,-88,1451,1500,160.9450,167.1400,None,None,-602.902960,57.742960,-0.042568,2024-08-06,2024-10-15,70 days,None,179.43480,163.42520,180.159429,162.049143
48,81,1500,1589,167.1400,180.1550,None,None,997.953210,56.261790,0.073713,2024-10-15,2025-02-25,133 days,None,163.42520,192.66600,162.049143,193.294000
49,-81,1589,1644,180.1550,161.3100,None,None,1471.127670,55.317330,0.100814,2025-02-25,2025-05-14,78 days,None,192.66600,159.48280,193.294000,158.414571
50,99,1644,1812,161.3100,334.9850,None,None,17095.558590,98.266410,1.070500,2025-05-14,2026-01-14,245 days,None,159.48280,316.84240,158.414571,317.436000
51,-99,1812,1816,334.9850,321.0950,None,None,1245.206160,129.903840,0.037547,2026-01-14,2026-01-21,7 days,None,316.84240,318.88520,317.436000,318.336857
52,107,1816,1839,321.0950,310.6400,None,None,-1253.876290,135.191290,-0.036495,2026-01-21,2026-02-24,34 days,None,318.88520,323.31280,318.336857,324.606857